/* double include preventer */
#ifndef _MSG_H
#define _MSG_H

/* file: msg.h, automatically generated by gencanoe.exe, Version: 5.02 */
/* configuration read from: C:\Users\nituser\AppData\Local\Temp\Cfg_Gen-1713011170546-6\OsProxyFiles-1713011814697-0\Os_ActiveEcuC.arxml.oil */
/* generation at  : Sat Apr 13 14:36:55 2024 */
/* Unlimited license 1234567890 for CANoeEmu Generic License */
/* Implementation: CANoeOsekEmu */
/* Version of general code: 5.31 */

#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif
#define osdVrmGenMajRelNum 5
#define osdVrmGenMinRelNum 2
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif


#endif   /* double include preventer */

/* END OF C:\nit-au-03\AUTOSAR_Exercises\AFS\Appl\GenDataVtt\msg.h */

